### PR TITLE
DL4J UI: Migrate from Play to Vertx

### LINKED ISSUE #8413: DL4J: UI functions on Java 8 only?
Running the Code:
`import org.deeplearning4j.ui.api.UIServer;

public class Test {
	public static void main(String[] args) {
		UIServer uiServer = UIServer.getInstance();
	}
}`
results in: 
java.lang.IllegalArgumentException: Don't know how to bind argument of type class net.jodah.typetools.TypeResolver$Unknown
	at play.routing.RoutingDsl.pathBindableFor(RoutingDsl.java:290)
	at play.routing.RoutingDsl.with(RoutingDsl.java:239)
	at play.routing.RoutingDsl.access$000(RoutingDsl.java:91)
	at play.routing.RoutingDsl$PathPatternMatcher.build(RoutingDsl.java:553)
	at play.routing.RoutingDsl$PathPatternMatcher.routingTo(RoutingDsl.java:360)
	at org.deeplearning4j.ui.play.PlayUIServer.createRouter(PlayUIServer.java:245)
	at play.core.server.JavaServerHelper$$anon$4.router(Server.scala:331)
	at play.BuiltInComponentsFromContext.createHttpRequestHandler(BuiltInComponentsFromContext.java:217)
	at play.libs.F$LazySupplier.get(F.java:372)
	at play.BuiltInComponentsFromContext.httpRequestHandler(BuiltInComponentsFromContext.java:205)
	at play.BuiltInComponentsFromContext.createApplication(BuiltInComponentsFromContext.java:138)
	at play.libs.F$LazySupplier.get(F.java:372)
	at play.BuiltInComponentsFromContext.application(BuiltInComponentsFromContext.java:125)
	at play.core.server.JavaServerHelper$.forRouter(Server.scala:330)
	at play.core.server.JavaServerHelper.forRouter(Server.scala)
	at play.server.Server$Builder.build(Server.java:231)
	at play.server.Server.forRouter(Server.java:135)
	at org.deeplearning4j.ui.play.PlayUIServer.runMain(PlayUIServer.java:194)
	at org.deeplearning4j.ui.api.UIServer.getInstance(UIServer.java:67)
	at org.deeplearning4j.ui.api.UIServer.getInstance(UIServer.java:45)
Attached is the pom file (as .txt to make it uploadable).
[pom.txt](https://github.com/eclipse/deeplearning4j/files/3855678/pom.txt)

### PR DESCRIPTION
**Pull request by AlexDBlack**
DL4J and Arbiter UIs done, tested and working.
No API changes for users, should be seamless - existing UI examples run OK without any modification.

Note that unlike Play, Vertx doesn't rely on Scala - so the module names have changed:
`deeplearning4j-ui_2.1x` -> `deeplearning4j-ui`
`deeplearning4j-play_2.1x` -> `deeplearning4j-vertx`
(Note that users should still just import deeplearning4j-ui as before)

Fixes: https://github.com/eclipse/deeplearning4j/issues/8413

### CODE REVIEW

File: arbiter/arbiter-ui/src/main/java/org/deeplearning4j/arbiter/ui/module/ArbiterModule.java [hunk 1]
```diff
@@ -197,23 +195,27 @@ public synchronized void onAttach(StatsStorage statsStorage) {
...
     }
 
-    private Result setSession(String newSessionID) {
+    private void setSession(String newSessionID, RoutingContext rc) {
         log.debug("Arbiter UI: Set to session {}", newSessionID);
 
         if (knownSessionIDs.containsKey(newSessionID)) {
             currentSessionID = newSessionID;
-            return ok();
+            rc.response().end();
```
Comment (agibsonccc) [inline arbiter/arbiter-ui/src/main/java/org/deeplearning4j/arbiter/ui/module/ArbiterModule.java:217]: Returning a status object might not be a bad idea here.

File: arbiter/arbiter-ui/src/main/java/org/deeplearning4j/arbiter/ui/module/ArbiterModule.java [hunk 2]
```diff
@@ -255,30 +257,32 @@ public void onDetach(StatsStorage statsStorage) {
...
+     * Return the last update time for the page
      */
-    private Result getLastUpdateTime(){
+    private void getLastUpdateTime(RoutingContext rc){
         //TODO - this forces updates on every request... which is fine, just inefficient
         long t = System.currentTimeMillis();
         UpdateStatus us = new UpdateStatus(t, t, t);
 
-        return ok(Json.toJson(us));
+        rc.response().putHeader("content-type", "application/json").end(Json.encode(us));
```
Comment (agibsonccc) [inline arbiter/arbiter-ui/src/main/java/org/deeplearning4j/arbiter/ui/module/ArbiterModule.java]: We might want to use our own object mappers here just to keep it consistent? This will use jackson underneath the covers.

File: arbiter/arbiter-ui/src/main/java/org/deeplearning4j/arbiter/ui/module/ArbiterModule.java [hunk 3]
```diff
@@ -292,7 +296,7 @@ private Result getModelLastUpdateTimes(String modelIDs){
             }
         }
 
-        return ok(Json.toJson(lastUpdateTimes));
+        rc.response().putHeader("content-type", "application/json").end(Json.encode(lastUpdateTimes));
```
Comment (agibsonccc) [inline arbiter/arbiter-ui/src/main/java/org/deeplearning4j/arbiter/ui/module/ArbiterModule.java]: Same thing  as above about json encoding.

File: deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/pom.xml [hunk 4]
```diff
@@ -619,4 +404,18 @@
             </dependency>
         </dependencies>
     </dependencyManagement>
-</project>
+
+    <build>
```
Comment (agibsonccc) [inline deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/pom.xml:419]: Wondering if we could use pluginManagement here instead? (Same with the other compiler declarations)

File: deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/main/java/org/deeplearning4j/ui/api/UIServer.java [hunk 5]
```diff
@@ -41,99 +38,81 @@
      * @return UI instance for this JVM
      * @throws RuntimeException if the instance has already started in a different mode (multi/single-session)
      */
-    public static synchronized UIServer getInstance() throws RuntimeException {
+    static UIServer getInstance() throws RuntimeException {
```
Comment (agibsonccc) [inline deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/main/java/org/deeplearning4j/ui/api/UIServer.java:41]: Any reason we got rid of the public declaration?

File: deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/test/java/org/deeplearning4j/ui/TestSameDiffUI.java [hunk 6]
```diff
@@ -0,0 +1,96 @@
+/*******************************************************************************
+ * Copyright (c) 2015-2019 Skymind, Inc.
```
Comment (agibsonccc) [inline deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/test/java/org/deeplearning4j/ui/TestSameDiffUI.java:2]: Copyright

File: deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/test/java/org/deeplearning4j/ui/TestSameDiffUI.java [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+import org.nd4j.graph.ui.LogFileWriter;
+import org.nd4j.linalg.api.buffer.DataType;
+import org.nd4j.linalg.api.ndarray.INDArray;
+import org.nd4j.linalg.factory.Nd4j;
+
+import java.io.File;
+import java.util.Arrays;
+
+@Ignore
+public class TestSameDiffUI {
```
Comment (agibsonccc) [inline deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/test/java/org/deeplearning4j/ui/TestSameDiffUI.java:38]: WIP?

**Review by agibsonccc — CHANGES_REQUESTED** [review]
Good so far!

File: arbiter/arbiter-ui/src/main/java/org/deeplearning4j/arbiter/ui/module/ArbiterModule.java (hunk 1 above)
Comment (AlexDBlack) [reply arbiter/arbiter-ui/src/main/java/org/deeplearning4j/arbiter/ui/module/ArbiterModule.java:217]: You mean like `.setStatusCode(HttpResponseStatus.OK.code())`?
It's 200/ok by default... https://vertx.io/blog/some-rest-with-vert-x/

File: deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/main/java/org/deeplearning4j/ui/api/UIServer.java (hunk 5 above)
Comment (AlexDBlack) [reply deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/main/java/org/deeplearning4j/ui/api/UIServer.java:41]: UIServer used to be an abstract class, now it's an interface (with java 8 static interface methods for consistency with the beta5 and earlier API). So it's public by definition.
Mainly because VertxUIServer class needs to extend AbstractVerticle for Vertx.
It's same API for users, they can still call UIServer.getInstance() as in beta5 and earlier.

File: arbiter/arbiter-ui/src/main/java/org/deeplearning4j/arbiter/ui/module/ArbiterModule.java (hunk 2 above)
Comment (AlexDBlack) [reply arbiter/arbiter-ui/src/main/java/org/deeplearning4j/arbiter/ui/module/ArbiterModule.java]: Fixed

File: deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/test/java/org/deeplearning4j/ui/TestSameDiffUI.java (hunk 6 above)
Comment (AlexDBlack) [reply deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/test/java/org/deeplearning4j/ui/TestSameDiffUI.java:2]: Fixed

File: deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/test/java/org/deeplearning4j/ui/TestSameDiffUI.java (hunk 7 above)
Comment (AlexDBlack) [reply deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/test/java/org/deeplearning4j/ui/TestSameDiffUI.java:38]: Cleaned up paths now. But this is otherwise just transferred over from master.
Overall SameDiff UI is WIP/POC stage, I've mainly been using it for debugging (to visualize complex graph structures). It works but it's by no means production ready.

File: deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/pom.xml (hunk 4 above)
Comment (AlexDBlack) [reply deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/pom.xml:419]: Done
