### PR TITLE
Eliminated error with resize implementation.

### LINKED ISSUE #8833: libnd4j:  helper::resizeFunctor: Non implemented yet.
During maping cpp op image_resize to Java class was noticed, that for following methods
1. ResizeLanczos5
2. ResizeMitchelcubic
3. ResizeArea

occured exception `java.lang.RuntimeException: helper::resizeFunctor: Non implemented yet.`
[full stacktrace
](https://gist.github.com/atuzhykov/31db95eedf7443072e4f2068e497794f
)

### PR DESCRIPTION
**Pull request by shugeo**
## What changes were proposed in this pull request?

Fixed  #8833 and #8455.

## How was this patch tested?

Proper tests were added.

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

### CODE REVIEW

File: libnd4j/include/ops/declarable/helpers/cpu/image_resize.cpp [hunk 1]
```diff
@@ -1000,7 +1000,7 @@ namespace helpers {
             case kResizeBilinear: return resizeBilinearFunctor(context, image, width, height, false, false, output); break;
             case kResizeNearest: return resizeNeighborFunctor(context, image, width, height, false, false, output); break;
             case kResizeBicubic: return resizeBicubicFunctor(context, image, width, height, preserveAspectRatio, antialias, output); break;
-            case kResizeArea: return resizeAreaFunctor(context, image, width, height, preserveAspectRatio, output);
+            case kResizeArea: return resizeAreaFunctor(context, image, width, height, preserveAspectRatio, output); break;
```
Comment (raver119) [inline libnd4j/include/ops/declarable/helpers/cpu/image_resize.cpp]: wtf? this PR changes nothing, since you have return statement before break.

**Review by raver119 — CHANGES_REQUESTED** [review]
This PR changes nothing.

File: libnd4j/include/ops/declarable/generic/images/image_resize.cpp [hunk 2]
```diff
@@ -34,53 +34,48 @@ namespace sd {
...
             REQUIRE_TRUE(size->lengthOf() == 2, 0, "resize_bilinear: Resize params is a pair of values, not %lld.", size->lengthOf());
-            width = size->e<int>(0);
-            height = size->e<int>(1);
-            if (block.getBArguments()->size()) {
-                preserveAspectRatio = B_ARG(0);
-                if (block.getBArguments()->size() > 1)
-                    antialias = B_ARG(1);
+            width = size->e<int>(1);
+            height = size->e<int>(0);
+            if (block.getBArguments()->size() == 2) {
```
Comment (raver119) [inline libnd4j/include/ops/declarable/generic/images/image_resize.cpp]: Please use `block.numB()` instead of `block.getBArguments()->size()`

File: libnd4j/include/ops/declarable/generic/images/resize_images.cpp [hunk 3]
```diff
@@ -0,0 +1,129 @@
+/*******************************************************************************
+ * Copyright (c) 2019 Konduit K.K.
```
Comment (raver119) [inline libnd4j/include/ops/declarable/generic/images/resize_images.cpp]: I've just checked, it's 2020 now.

File: libnd4j/include/ops/declarable/generic/images/resize_images.cpp [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+
+                    REQUIRE_TRUE(methodT->isZ() && methodT->isScalar(), 0, "resize_images: Method tensor should be integer scalar, but rank of %i tensor given.", methodT->rankOf());
+                    method = methodT->e<int>(0);
+                }
+                else if (block.getIArguments()->size() == 1) {
+                    method = I_ARG(0);
+                }
+            }
+            else {
+                REQUIRE_TRUE(block.getIArguments()->size() > 1 && block.getIArguments()->size() < 4, 0, "resize_images: Method and size should be given properly.");
```
Comment (raver119) [inline libnd4j/include/ops/declarable/generic/images/resize_images.cpp]: Same as above

File: libnd4j/include/ops/declarable/generic/images/resize_images.cpp [hunk 5]
```diff
@@ -0,0 +1,129 @@
...
+            }
+
+            double ratio = shape::sizeAt(in, 1) / (0.0 + shape::sizeAt(in, 2));
+            if (block.getBArguments()->size() > 1) {
+                if (B_ARG(1)) {
+                    width = math::nd4j_ceil<double, int>(height / ratio);
+                }
+            }
+
+            ALLOCATE(outputShape, block.getWorkspace(), shape::shapeInfoLength(4), Nd4jLong);
```
Comment (raver119) [inline libnd4j/include/ops/declarable/generic/images/resize_images.cpp]: Are you sure there's no leak here? I don't see any release or whatever. Maybe use std::array instead?

File: libnd4j/include/ops/declarable/generic/images/resize_images.cpp [hunk 6]
```diff
@@ -0,0 +1,129 @@
...
+            outputShape[0] = 4;
+            outputShape[1] = in[1];
+            outputShape[2] = height;
+            outputShape[3] = width;
+            outputShape[4] = in[4];
+            ShapeUtils::updateStridesAndType(outputShape, DataType::FLOAT32, shape::order(in));
```
Comment (raver119) [inline libnd4j/include/ops/declarable/generic/images/resize_images.cpp]: Why it's fixed DataType::FLOAT32?

File: libnd4j/include/ops/declarable/generic/images/resize_images.cpp [hunk 7]
```diff
@@ -0,0 +1,129 @@
...
+
+            shapeList->push_back(CONSTANT(outputShape));
+            return shapeList;
+        }
+        DECLARE_TYPES(resize_images) {
+            getOpDescriptor()
+                    ->setAllowedInputTypes(0, {ALL_FLOATS, ALL_INTS})
+                    ->setAllowedInputTypes(1, {ALL_INTS})
+                    ->setAllowedOutputTypes({ALL_FLOATS});
```
Comment (raver119) [inline libnd4j/include/ops/declarable/generic/images/resize_images.cpp]: Same question. You have fixed FLOAT32 output in shape function, and allow ALL_FLOATS during validation. WTF?

File: libnd4j/tests_cpu/layers_tests/DeclarableOpsTests10.cpp [hunk 8]
```diff
@@ -1528,6 +1551,105 @@ TEST_F(DeclarableOpsTests10, ImageResizeBilinear_Test01) {
 
 }
 
+TEST_F(DeclarableOpsTests10, ResizeImages_Test1) {
+
+    NDArray input = NDArrayFactory::create<float>('c', {2, 4, 5, 3});
+    input.linspace(1.);
+
+    auto expected = NDArrayFactory::create<float>('c', {2, 7, 9, 3}, {
+            1., 2., 3., 2.6666667, 3.6666667,
```
Comment (raver119) [inline libnd4j/tests_cpu/layers_tests/DeclarableOpsTests10.cpp]: Either make this array double, or add f literal. MSVC will be very disappointed otherwise.

**Review by raver119 — CHANGES_REQUESTED** [review]

File: libnd4j/include/ops/declarable/generic/images/resize_images.cpp (hunk 5 above)
Comment (shugeo) [reply libnd4j/include/ops/declarable/generic/images/resize_images.cpp]: Refactored to eliminate memory leaks

File: libnd4j/tests_cpu/layers_tests/DeclarableOpsTests10.cpp (hunk 8 above)
Comment (shugeo) [reply libnd4j/tests_cpu/layers_tests/DeclarableOpsTests10.cpp]: Fixed to avoid MSVC compilation issues.
