### PR TITLE
- correct reshape op for empty shapes

### LINKED ISSUE #8592: Modification required for empty reshape with -1s
Following up on this issue: https://github.com/eclipse/deeplearning4j/issues/8572

Turns out I was wrong regarding TF's behaviour for reshape with -1 and 0s.

Seems like the behaviour is "keep the product of the non-0 (and non -1) elements the same".

Here's some test cases:
```
shapes =  [[2,0], [10,0],    [10, 0],  [2,0,0,10], [10, 0],   [0, 0, 10],  [0,2,10]]
reshape = [[2,-1], [2,0,-1], [5,2,-1], [2,0,-1],   [-1, 2, 0], [2, -1, 0], [2, 0, 0, 0, -1]]
for i in range(len(shapes)):
    tf.reset_default_graph()
    emptyFloat = tf.constant([], shape=shapes[i], dtype=tf.float32)
    x = tf.reshape(emptyFloat, reshape[i])
    sess = tf.Session()
    out = sess.run([x])
    print(str(shapes[i]) + ".reshape(" + str(reshape[i]) + ") = " + str(out[0].shape))
```

```
[2, 0].reshape([2, -1]) = (2, 0)
[10, 0].reshape([2, 0, -1]) = (2, 0, 5)
[10, 0].reshape([5, 2, -1]) = (5, 2, 0)
[2, 0, 0, 10].reshape([2, 0, -1]) = (2, 0, 10)
[10, 0].reshape([-1, 2, 0]) = (5, 2, 0)
[0, 0, 10].reshape([2, -1, 0]) = (2, 5, 0)
[0, 2, 10].reshape([2, 0, 0, 0, -1]) = (2, 0, 0, 0, 10)
```

### PR DESCRIPTION
**Pull request by shyrma**
make reshape op logic to be close to tf behavior, 
for example take into account possible reshape combinations like this
[1, 2, 0].reshape([2, 0, -1]) = (2, 0, 1)

Fixes: https://github.com/eclipse/deeplearning4j/issues/8592

### CODE REVIEW

File: libnd4j/include/ops/declarable/generic/shape/reshape.cpp [hunk 1]
```diff
@@ -81,43 +81,79 @@ DECLARE_SHAPE_FN(reshape) {
 
     REQUIRE_TRUE(!reshapeArgs.empty() || x->lengthOf() == 1, 0, "Reshape buffer should have at least 1 dimension !");
 
-    Nd4jLong xLen = x->lengthOf();
-    if(x->isEmpty()) {
-        xLen = 1;
-        for (uint i = 0; i < x->rankOf(); ++i)                            // take into account possible empty shapes
-            if(x->sizeAt(i) != 0)
-                xLen *= x->sizeAt(i);
+    // Nd4jLong xLen = x->lengthOf();
```
Comment (raver119) [inline libnd4j/include/ops/declarable/generic/shape/reshape.cpp:84]: Just delete unused code. Don't comment it out.

**Review by raver119 — CHANGES_REQUESTED** [review]

**Review by AlexDBlack — APPROVED** [review]
